### ISSUE TITLE
Where did bem.html go?

### ISSUE THREAD

**Issue by laurinenas** [Integralist/integralist.github.com#5]
Hi @Integralist ,

Firstly, thank you for the wonderful content!

This blog is linked from getbem.com, but the link is no longer working. [The people](https://github.com/getbem/getbem.com/issues/146) are considering to link to waybackmachine or some of the reposts. Was there a reason to remove it, or could we possibly get the article back online?

Thank you for your response!

**Comment by Integralist** [comment]
Thanks for your patience @laurinenas -- I have a 10 month old baby and so I've not been able to find the time between him and work to get around to this. But I've put the article back online now under a slightly modifed path...

```
/posts/bem/
```

I deploy my site from GitHub via Netlify and it seems there are problems with their CI that means the post isn't deployed yet. I'll keep an eye on it and let you know once it's resolved.

**Comment by Integralist** [comment]
OK looks to have worked now!

https://www.integralist.co.uk/posts/bem/

**Comment by laurinenas** [comment]
Thank you!

It does work just fine.

Best wishes to you and your family! ❤️
